In [23]:
#Importamos las funciones

import pandas as pd
import numpy as np

# Leer archivo

In [24]:
def f_leer_archivo(param_archivo):
     # Leer archivo de datos y guardarlo en un DataFrame
    df_data = pd.read_excel('archivos/' + param_archivo, sheet_name='Hoja1')
    df_data = df_data.loc[df_data['Type']!='balance']
    
    # elegir solo renglones en los que la columna type == buy | type == sell

    # Convertir en minusculas el nombre de las columnas
    df_data.columns = [list(df_data.columns)[i].lower()
                       for i in range(0, len(df_data.columns))]
    # Asegurar que ciertas son del tipo numerico
    numcols = ['s/l', 't/p', 'commission', 'openprice', 'closeprice', 'profit', 'size', 'swap',
              'taxes', 'order']

    df_data[numcols] = df_data[numcols].apply(pd.to_numeric)

    #print(df_data)
    return df_data

In [25]:
# Leemos el archivo por medio de la funcion creada y lo imprimimos
df_archivo = f_leer_archivo(param_archivo="archivo_tradeview_1.xlsx")
df_archivo  = df_archivo.reset_index()
df_archivo .head()

,index,order,opentime,type,size,symbol,openprice,s/l,t/p,closetime,closeprice,commission,taxes,swap,profit
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34

# Funcion pips size

In [26]:
# -- ------------------------------------------------------ FUNCION: Pips por instrumento -- #
# -- ------------------------------------------------------------------------------------ -- #
# -- calcular el tama√±o de los pips por instrumento

def f_pip_size(param_ins):
    """
           Parameters
       ----------
       param_ins : str : nombre de instrumento
       Returns
       -------
       Debugging
       -------
       param_ins = 'usdjpy'
       """

    # encontrar y eliminar un guion bajo
    # inst = param_ins.replace('_', '')

    # transformar a minusculas
    inst = param_ins.lower()

    # lista de pips por instrumento
    pips_inst = {'usdjpy': 100, 'gbpjpy': 100, 'eurjpy': 100, 'cadjpy': 100,
                 'chfjpy': 100,
                 'eurusd': 10000, 'gbpusd': 10000, 'usdcad': 10000, 'usdmxn': 10000,
                 'audusd': 10000, 'nzdusd': 10000,
                 'usdchf': 10000,
                 'eurgbp': 10000, 'eurchf': 10000, 'eurnzd': 10000, 'euraud': 10000,
                 'gbpnzd': 10000, 'gbpchf': 10000, 'gbpaud': 10000,
                 'audnzd': 10000, 'nzdcad': 10000, 'audcad': 10000,
                 'xauusd': 10, 'xagusd': 10, 'btcusd': 10, 'wticousd':10,'natgasusd':10}

    return pips_inst[inst]

In [27]:
f_pip_size(param_ins = 'eurusd')

10000

# Columna de diferencias de tiempo

In [28]:
# Importamos las librerias necesarias para crear esta funcion

from datetime import  datetime
from datetime import timedelta

# Se crea la funcion

def f_columnas_tiempos():
    
    # Se toman las columnas de tiempo en donde se abrio y cerro la posicion y creamos un nuevo DataFrame con estas columnas
    
    df_new = df_archivo[['opentime','closetime']]
    df = pd.DataFrame(data=df_new)
    df['opentime'] = pd.to_datetime(df_new['opentime'])
    df['closetime'] = pd.to_datetime(df_new['closetime'])

    # Se crea una nueva variable que resta los tiempos y despues los convertimos a segundos para al final agragarlos al DataFrame original
    
    Time = df['closetime'] - df['opentime']
    Time = Time.dt.seconds
    Time = pd.DataFrame(Time)
    df_archivo['Time'] = Time
    return df_archivo

In [29]:
# Corremos la funcion e imprimimos el DataFrame para observar los resultados

f_columnas_tiempos()

,index,order,opentime,type,size,symbol,openprice,s/l,t/p,closetime,closeprice,commission,taxes,swap,profit,Time
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92,8291
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73,48716
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00,5745
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27,48415
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,79,25148355,2019.09.24 20:09:52,sell,0.06,xauusd,1532.02000,1538.000,0.0000,2019.09.24 21:18:43,1525.66000,0.0,0,0,38.16,4131
80,80,25148480,2019.09.24 20:11:20,sell,0.02,xauusd,1531.50000,1538.000,0.0000,2019.09.24 21:18:46,1525.63000,0.0,0,0,11.74,4046
81,81,25148522,2019.09.24 20:12:41,sell,0.01,xauusd,1531.86000,1538.000,0.0000,2019.09.24 21:18:49,1525.66000,0.0,0,0,6.20,3968
82,82,25159294,2019.09.25 01:53:47,sell,0.06,xauusd,1531.06000,1537.000,0.0000,2019.09.25 15:24:31,1527.40000,0.0,0,0,21.96,48644
83,83,25159303,2019.09.25 01:54:46,sell,0.01,xauusd,1531.28000,1537.000,0.0000,2019.09.25 15:24:35,1527.36000,0.0,0,0,3.92,48589

# Columna de Pips

In [30]:
# Quitamos todos los '-2' que se tenian en los item para que no nos afecten mas adelante

df_archivo['symbol'] = df_archivo['symbol'].replace('usdmxn-2','usdmxn').replace('wticousd-2','wticousd').replace('xauusd-2','xauusd').replace('xagusd-2','xagusd').replace('natgasusd-2','natgasusd').replace('gbpusd-2','gbpusd').replace('eurusd-2','eurusd')

In [31]:
# Creamos una funcion para contar los pips ganados o perdidos

def f_columnas_pips():
    
    # Se creo un nuevo DataFrame con las columnas que se iban a necesitar
    Pips = df_archivo[['symbol','type','openprice','closeprice']]
    Pips.index = np.arange(0,len(Pips))
    
    pip = []
    contador = 0
    
    # Entramos a un ciclo donde dependiendo del type y si es buy o sell es lo que la funcion hara e ira guardando los resultados en un nuevo arreglo
    
    for i in range(0,len(Pips)):
        if Pips['type'][i] == 'buy':
            f = Pips['symbol'][contador]
            multiplicador = f_pip_size(param_ins = f)
            pip.append((Pips['closeprice'][i] - Pips['openprice'][i]) * multiplicador)
        else:
            f = Pips['symbol'][contador]
            multiplicador = f_pip_size(param_ins = f)
            pip.append((Pips['openprice'][i] - Pips['closeprice'][i])*multiplicador)
        contador = contador + 1
           
    # El arreglo se convierte en un DataFrame que despues sera agregado a nuestro DataFrame original
    
    Pips = pd.DataFrame(pip)
    df_archivo['Pips'] = Pips
    return df_archivo

In [32]:
# Corremos la funcion e imprimimos el DataFrame para observar los resultados

f_columnas_pips()
df_archivo

,index,order,opentime,type,size,symbol,openprice,s/l,t/p,closetime,closeprice,commission,taxes,swap,profit,Time,Pips
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92,8291,44.8
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73,48716,-29.0
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00,5745,10.6
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27,48415,2.7
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34,116,-3.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,79,25148355,2019.09.24 20:09:52,sell,0.06,xauusd,1532.02000,1538.000,0.0000,2019.09.24 21:18:43,1525.66000,0.0,0,0,38.16,4131,63.6
80,80,25148480,2019.09.24 20:11:20,sell,0.02,xauusd,1531.50000,1538.000,0.0000,2019.09.24 21:18:46,1525.63000,0.0,0,0,11.74,4046,58.7
81,81,25148522,2019.09.24 20:12:41,sell,0.01,xauusd,1531.86000,1538.000,0.0000,2019.09.24 21:18:49,1525.66000,0.0,0,0,6.20,3968,62.0
82,82,25159294,2019.09.25 01:53:47,sell,0.06,xauusd,1531.06000,1537.000,0.0000,2019.09.25 15:24:31,1527.40000,0.0,0,0,21.96,48644,36.6
83,83,25159303,2019.09.25 01:54:46,sell,0.01,xauusd,1531.28000,1537.000,0.0000,2019.09.25 15:24:35,1527.36000,0.0,0,0,3.92,48589,39.2

# Tabla Estadisticas

### df_1_tabla

In [33]:
Pips = df_archivo[['symbol','type','openprice','closeprice']]
Pips.index = np.arange(0,len(Pips))
Win = 0   #Ganadoras
Lose = 0  #Perdedoras
WinB = 0  #Ganadoras Compra
WinS = 0 #Ganadoras de Venta
LoseB = 0 #Perdedora Compra
LoseS = 0 #Perdedoras Venta


# Entramos a un ciclo en donde iremos contando los trades ganados y los perdidos y se iran agregando a la variable correspondiente

for i in range(0,len(df_archivo)):
    if df_archivo['type'][i] == 'buy':
        if df_archivo['Pips'][i] > 0:
            Win = Win + 1
            WinB = WinB + 1
        else:
            Lose = Lose + 1 
            LoseB = LoseB + 1
    else:
        if df_archivo['Pips'][i] > 0:
            Win = Win + 1
            WinS = WinS + 1
        else:
            Lose = Lose + 1 
            LoseS = LoseS + 1

# Se realizan las operaciones necesarias para poder obtener los resultados(divisiones, promedios...)

Ops_totales = len(Pips)
r_efectividad  = Win / Ops_totales
r_porcion = Lose / Win
r_efectividad_c = WinB / Ops_totales
r_efectividad_v = WinS / Ops_totales
Media_Profit = df_archivo['profit'].mean()
Media_Pips = df_archivo['Pips'].mean()

#Creamos una tabla en donde mostremos los resultados con sus respectivos nombres de las variables

df_1_tabla = pd.DataFrame (columns = ['Medida','Valor','Descripcion'])
df_1_tabla.Medida = ['Ops totales','Ganadoras','Ganadoras_c','Ganadoras_v','Perdedoras','Perdedoras_c','Perdedoras_v','Media (Profit)','Media (Pips)','r_efectividad','r_proporcion','r_efectividad_c','r_efectividad_v']
df_1_tabla.Descripcion = ['Operaciones totales','Operaciones ganadoras','Operaciones ganadoras de compra','Operaciones perdedoras de venta','Operaciones perdedoras','Operaciones perdedoras de compra','Operaciones perdedoras de venta','Mediana de profit de operaciones','Mediana de pips de operaciones','Ganadoras Totales/Operaciones Totales','Perdedoras Totales/Ganadoras Totales','Ganadoras Compras/Operaciones Totales','Ganadoras Ventas/ Operaciones Totales']
df_1_tabla.Valor = [Ops_totales, Win, WinB, WinS, Lose, LoseB, LoseS, Media_Profit, Media_Pips , r_efectividad, r_porcion, r_efectividad_c, r_efectividad_v,]
df_1_tabla

             Medida      Valor                            Descripcion
0       Ops totales  84.000000                    Operaciones totales
1         Ganadoras  46.000000                  Operaciones ganadoras
2       Ganadoras_c  20.000000        Operaciones ganadoras de compra
3       Ganadoras_v  26.000000        Operaciones perdedoras de venta
4        Perdedoras  38.000000                 Operaciones perdedoras
5      Perdedoras_c  19.000000       Operaciones perdedoras de compra
6      Perdedoras_v  19.000000        Operaciones perdedoras de venta
7    Media (Profit)   3.025357       Mediana de profit de operaciones
8      Media (Pips)  29.066667         Mediana de pips de operaciones
9     r_efectividad   0.547619  Ganadoras Totales/Operaciones Totales
10     r_proporcion   0.826087   Perdedoras Totales/Ganadoras Totales
11  r_efectividad_c   0.238095  Ganadoras Compras/Operaciones Totales
12  r_efectividad_v   0.309524  Ganadoras Ventas/ Operaciones Totales

### df_1_ranking

In [34]:
# Se agrupan los valores de item donde se cuentan cuales fueron mayores a 1 en el profit para identificar que son ganadoras

efec = df_archivo[['symbol','profit']]
count_movi = efec.groupby('symbol').count()
count_posit = efec[efec['profit'] > 0].groupby([efec['symbol']])
count_posit = count_posit.count()

# Se dividen las posiciones ganadas entre las totales y se multiplican por 100 para obtenerlo en porcentaje

Efectividad = ((count_posit['profit'] / count_movi['profit'] ) * 100).round(4)
Efectividad = pd.DataFrame(Efectividad)
Porcentaje  = [str(l) + "%" for l in Efectividad.profit]
Efectividad.profit = Porcentaje

# Creamos un nuevo DaraFrame con los resultados obtenidos

Ratio_efect = pd.DataFrame(Porcentaje)
Efectividad.rename(columns = {'profit':'rank'})
New = Efectividad.reset_index()
df_1_ranking = New.rename(columns={'symbol':'symbol'})
df_1_ranking

    symbol    profit
0   audusd  33.3333%
1   btcusd    100.0%
2   eurgbp    100.0%
3   eurjpy  28.5714%
4   eurusd  47.8261%
5   gbpjpy     25.0%
6   gbpusd  66.6667%
7   usdcad  28.5714%
8   usdjpy     60.0%
9   usdmxn     80.0%
10  xauusd  73.6842%

In [37]:
#Se crea una funcion que contenga un diccionario con las dos tablas anteriores que obtuvimos

def f_estadisticas_ba():
    Pips = df_archivo[['symbol','type','openprice','closeprice']]
    Pips.index = np.arange(0,len(Pips))
    Win = 0   #Ganadoras
    Lose = 0  #Perdedoras
    WinB = 0  #Ganadoras Compra
    WinS = 0 #Ganadoras de Venta
    LoseB = 0 #Perdedora Compra
    LoseS = 0 #Perdedoras Venta


    # Entramos a un ciclo en donde iremos contando los trades ganados y los perdidos y se iran agregando a la variable correspondiente

    for i in range(0,len(df_archivo)):
        if df_archivo['type'][i] == 'buy':
            if df_archivo['Pips'][i] > 0:
                Win = Win + 1
                WinB = WinB + 1
            else:
                Lose = Lose + 1 
                LoseB = LoseB + 1
        else:
            if df_archivo['Pips'][i] > 0:
                Win = Win + 1
                WinS = WinS + 1
            else:
                Lose = Lose + 1 
                LoseS = LoseS + 1

    # Se realizan las operaciones necesarias para poder obtener los resultados(divisiones, promedios...)

    Ops_totales = len(Pips)
    r_efectividad  = Win / Ops_totales
    r_porcion = Lose / Win
    r_efectividad_c = WinB / Ops_totales
    r_efectividad_v = WinS / Ops_totales
    Media_Profit = df_archivo['profit'].mean()
    Media_Pips = df_archivo['Pips'].mean()

    #Creamos una tabla en donde mostremos los resultados con sus respectivos nombres de las variables

    df_1_tabla = pd.DataFrame (columns = ['Medida','Valor','Descripcion'])
    df_1_tabla.Medida = ['Ops totales','Ganadoras','Ganadoras_c','Ganadoras_v','Perdedoras','Perdedoras_c','Perdedoras_v','Media (Profit)','Media (Pips)','r_efectividad','r_proporcion','r_efectividad_c','r_efectividad_v']
    df_1_tabla.Descripcion = ['Operaciones totales','Operaciones ganadoras','Operaciones ganadoras de compra','Operaciones perdedoras de venta','Operaciones perdedoras','Operaciones perdedoras de compra','Operaciones perdedoras de venta','Mediana de profit de operaciones','Mediana de pips de operaciones','Ganadoras Totales/Operaciones Totales','Perdedoras Totales/Ganadoras Totales','Ganadoras Compras/Operaciones Totales','Ganadoras Ventas/ Operaciones Totales']
    df_1_tabla.Valor = [Ops_totales, Win, WinB, WinS, Lose, LoseB, LoseS, Media_Profit, Media_Pips , r_efectividad, r_porcion, r_efectividad_c, r_efectividad_v,]
    #df_1_tabla
    
    # Se agrupan los valores de item donde se cuentan cuales fueron mayores a 1 en el profit para identificar que son ganadoras

    efec = df_archivo[['symbol','profit']]
    count_movi = efec.groupby('symbol').count()
    count_posit = efec[efec['profit'] > 0].groupby([efec['symbol']])
    count_posit = count_posit.count()

    # Se dividen las posiciones ganadas entre las totales y se multiplican por 100 para obtenerlo en porcentaje

    Efectividad = ((count_posit['profit'] / count_movi['profit'] ) * 100).round(4)
    Efectividad = pd.DataFrame(Efectividad)
    Porcentaje  = [str(l) + "%" for l in Efectividad.profit]
    Efectividad.profit = Porcentaje

    # Creamos un nuevo DaraFrame con los resultados obtenidos

    Ratio_efect = pd.DataFrame(Porcentaje)
    Efectividad.rename(columns = {'profit':'rank'})
    New = Efectividad.reset_index()
    df_1_ranking = New.rename(columns={'symbol':'symbol'})
    
    
    Diccionario = {"Estadistica":df_1_tabla,"Efectividad":df_1_ranking}  
    return Diccionario

In [38]:
f_estadisticas_ba()

{'Estadistica':              Medida      Valor                            Descripcion
 0       Ops totales  84.000000                    Operaciones totales
 1         Ganadoras  46.000000                  Operaciones ganadoras
 2       Ganadoras_c  20.000000        Operaciones ganadoras de compra
 3       Ganadoras_v  26.000000        Operaciones perdedoras de venta
 4        Perdedoras  38.000000                 Operaciones perdedoras
 5      Perdedoras_c  19.000000       Operaciones perdedoras de compra
 6      Perdedoras_v  19.000000        Operaciones perdedoras de venta
 7    Media (Profit)   3.025357       Mediana de profit de operaciones
 8      Media (Pips)  29.066667         Mediana de pips de operaciones
 9     r_efectividad   0.547619  Ganadoras Totales/Operaciones Totales
 10     r_proporcion   0.826087   Perdedoras Totales/Ganadoras Totales
 11  r_efectividad_c   0.238095  Ganadoras Compras/Operaciones Totales
 12  r_efectividad_v   0.309524  Ganadoras Ventas/ Operaciones Totales,
 'Efectividad':     symbol    profit
 0   audusd  33.3333%
 1   btcusd    100.0%
 2   eurgbp    100.0%
 3   eurjpy  28.5714%
 4   eurusd  47.8261%
 5   gbpjpy     25.0%
 6   gbpusd  66.6667%
 7   usdcad  28.5714%
 8   usdjpy     60.0%
 9   usdmxn     80.0%
 10  xauusd  73.6842%}

# Medidas de atribucion al desempe√±o

# Capital_acm

In [39]:
def capital_acm(datos): 
    capital = 5000
    capital_acm = []
    for i in range(0,len(df_archivo)):
        capital = df_archivo['profit'][i] + capital
        capital_acm.append(capital)

    Capital_acm = pd.DataFrame(capital_acm)
    df_archivo['Capital_acm'] = Capital_acm
    df_archivo
    return datos

# f_profit_diario:

In [46]:
Fechas = [df_archivo["closetime"][l][:10] for l in range(df_archivo.shape[0])]
timestamp = pd.DataFrame(columns = ('timestamp','Profit_d'))
timestamp.timestamp = Fechas
timestamp.Profit_d = df_archivo['profit']
profit_diario = timestamp.groupby('timestamp').sum()
profit_diario = profit_diario.reset_index()
Fecha = pd.to_datetime(profit_diario['timestamp'])
profit_diario['timestamp'] = Fecha
profit_diario

    timestamp  Profit_d
0  2019-08-27     27.61
1  2019-08-28      5.00
2  2019-08-29     -1.52
3  2019-08-30    -17.16
4  2019-09-02    -33.90
5  2019-09-03   -137.90
6  2019-09-04     29.11
7  2019-09-06      7.27
8  2019-09-11     44.24
9  2019-09-12     -7.61
10 2019-09-13     64.68
11 2019-09-16    106.68
12 2019-09-17     -2.64
13 2019-09-18     13.62
14 2019-09-19     32.85
15 2019-09-20     14.46
16 2019-09-24     50.29
17 2019-09-25     68.88
18 2019-09-26    -16.67
19 2019-09-27      6.84

In [62]:
def f_profit_diario(datos): 
    Fechas = [df_archivo["closetime"][l][:10] for l in range(df_archivo.shape[0])]
    timestamp = pd.DataFrame(columns = ('Fecha','Profit'))
    timestamp.Fecha = Fechas
    timestamp.Profit = df_archivo['profit']
    profit_diario = timestamp.groupby('Fecha').sum()
    profit_diario = profit_diario.reset_index()
    Fecha = pd.to_datetime(profit_diario['Fecha'])
    profit_diario['Fecha'] = Fecha

    profit_diario_1 = pd.DataFrame (columns = ['Fecha','Profit'])
    profit_diario_1.Fecha = pd.date_range(start="2019.08.27",end="2019.09.25")

    df = pd.concat([profit_diario, profit_diario_1])
    df = df.reset_index(drop=True)

    Agrupados = df.groupby('Fecha')
    Agrupados = Agrupados.mean()
    f_profit_diario = Agrupados.fillna(0)

    f_profit_diario = f_profit_diario.reset_index()
    capital = 5000
    capital_acm_d = []
    for i in range(0,len(f_profit_diario)):
        capital = f_profit_diario['Profit'][i] + capital
        capital_acm_d.append(capital)

    profit_acm_d = pd.DataFrame(capital_acm_d)
    f_profit_diario['profit_acm_d'] = profit_acm_d
    f_profit_diario

        Fecha  Profit  profit_acm_d
0  2019-08-27   27.61       5027.61
1  2019-08-28    5.00       5032.61
2  2019-08-29   -1.52       5031.09
3  2019-08-30  -17.16       5013.93
4  2019-08-31    0.00       5013.93
5  2019-09-01    0.00       5013.93
6  2019-09-02  -33.90       4980.03
7  2019-09-03 -137.90       4842.13
8  2019-09-04   29.11       4871.24
9  2019-09-05    0.00       4871.24
10 2019-09-06    7.27       4878.51
11 2019-09-07    0.00       4878.51
12 2019-09-08    0.00       4878.51
13 2019-09-09    0.00       4878.51
14 2019-09-10    0.00       4878.51
15 2019-09-11   44.24       4922.75
16 2019-09-12   -7.61       4915.14
17 2019-09-13   64.68       4979.82
18 2019-09-14    0.00       4979.82
19 2019-09-15    0.00       4979.82
20 2019-09-16  106.68       5086.50
21 2019-09-17   -2.64       5083.86
22 2019-09-18   13.62       5097.48
23 2019-09-19   32.85       5130.33
24 2019-09-20   14.46       5144.79
25 2019-09-21    0.00       5144.79
26 2019-09-22    0.00       5144.79
27 2019-09-23    0.00       5144.79
28 2019-09-24   50.29       5195.08
29 2019-09-25   68.88       5263.96
30 2019-09-26  -16.67       5247.29
31 2019-09-27    6.84       5254.13

# f_estadisticas_mad

## Sharpe Ratio:

In [63]:
## Sharpe Ratio:
# rp : Promedio de los rendimientos logaritmicos del profit_acm_d
rp_0 = np.log(f_profit_diario['profit_acm_d']/f_profit_diario['profit_acm_d'].shift(1))
rp = rp_0.mean()

rf = .08

#sdp: Desviacion estandar de rp
sdp = np.std(rp_0)

sharpe = (rp - rf)/sdp
sharpe

-10.135163974610002

## Sortino Ratio(Posiciones Compra):
mar = 30%

# Graficas

In [64]:
df_1_ranking

    symbol    profit
0   audusd  33.3333%
1   btcusd    100.0%
2   eurgbp    100.0%
3   eurjpy  28.5714%
4   eurusd  47.8261%
5   gbpjpy     25.0%
6   gbpusd  66.6667%
7   usdcad  28.5714%
8   usdjpy     60.0%
9   usdmxn     80.0%
10  xauusd  73.6842%