In [1]:
import pandas as pd
import numpy as np

In [2]:
def f_leer_archivo(param_archivo):
     # Leer archivo de datos y guardarlo en un DataFrame
    df_data = pd.read_excel('archivos/' + param_archivo, sheet_name='Hoja1')
    df_data = df_data.loc[df_data['Type']!='balance']
    
    # elegir solo renglones en los que la columna type == buy | type == sell

    # Convertir en minusculas el nombre de las columnas
    df_data.columns = [list(df_data.columns)[i].lower()
                       for i in range(0, len(df_data.columns))]
    # Asegurar que ciertas son del tipo numerico
    numcols = ['s/l', 't/p', 'commission', 'openprice', 'closeprice', 'profit', 'size', 'swap',
              'taxes', 'order']

    df_data[numcols] = df_data[numcols].apply(pd.to_numeric)

    #print(df_data)
    return df_data

In [3]:
df_archivo = f_leer_archivo(param_archivo="archivo_tradeview_1.xlsx")
df_archivo = df_archivo.reset_index()
df_archivo.head()

,index,order,open time,type,size,item,openprice,s/l,t/p,close time,closeprice,commission,taxes,swap,profit
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34

In [4]:
# -- ------------------------------------------------------ FUNCION: Pips por instrumento -- #
# -- ------------------------------------------------------------------------------------ -- #
# -- calcular el tama√±o de los pips por instrumento

def f_pip_size(param_ins):
    """
           Parameters
       ----------
       param_ins : str : nombre de instrumento
       Returns
       -------
       Debugging
       -------
       param_ins = 'usdjpy'
       """

    # encontrar y eliminar un guion bajo
    # inst = param_ins.replace('_', '')

    # transformar a minusculas
    inst = param_ins.lower()

    # lista de pips por instrumento
    pips_inst = {'usdjpy': 100, 'gbpjpy': 100, 'eurjpy': 100, 'cadjpy': 100,
                 'chfjpy': 100,
                 'eurusd': 10000, 'gbpusd': 10000, 'usdcad': 10000, 'usdmxn': 10000,
                 'audusd': 10000, 'nzdusd': 10000,
                 'usdchf': 10000,
                 'eurgbp': 10000, 'eurchf': 10000, 'eurnzd': 10000, 'euraud': 10000,
                 'gbpnzd': 10000, 'gbpchf': 10000, 'gbpaud': 10000,
                 'audnzd': 10000, 'nzdcad': 10000, 'audcad': 10000,
                 'xauusd': 10, 'xagusd': 10, 'btcusd': 10, 'wticousd':10,'natgasusd':10}

    return pips_inst[inst]

In [5]:
f_pip_size(param_ins = 'eurusd')

10000

In [6]:
df_new = df_archivo[['open time','close time']]
df_new.head()

             open time           close time
0  2019.08.27 06:57:50  2019.08.27 09:16:01
1  2019.08.27 17:06:20  2019.08.29 06:38:16
2  2019.08.27 19:25:39  2019.08.28 21:01:24
3  2019.08.28 17:11:33  2019.08.29 06:38:28
4  2019.08.29 06:35:27  2019.08.29 06:37:23

In [7]:
from datetime import  datetime
from datetime import timedelta
df = pd.DataFrame(data=df_new)
df['open time'] = pd.to_datetime(df_new['open time'])
df['close time'] = pd.to_datetime(df_new['close time'])

Time = df['close time'] - df['open time']
Time = Time.dt.seconds
Time = pd.DataFrame(Time)
df_archivo['Time'] = Time
df_archivo

,index,order,open time,type,size,item,openprice,s/l,t/p,close time,closeprice,commission,taxes,swap,profit,Time
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92,8291
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73,48716
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00,5745
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27,48415
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,79,25148355,2019.09.24 20:09:52,sell,0.06,xauusd,1532.02000,1538.000,0.0000,2019.09.24 21:18:43,1525.66000,0.0,0,0,38.16,4131
80,80,25148480,2019.09.24 20:11:20,sell,0.02,xauusd,1531.50000,1538.000,0.0000,2019.09.24 21:18:46,1525.63000,0.0,0,0,11.74,4046
81,81,25148522,2019.09.24 20:12:41,sell,0.01,xauusd,1531.86000,1538.000,0.0000,2019.09.24 21:18:49,1525.66000,0.0,0,0,6.20,3968
82,82,25159294,2019.09.25 01:53:47,sell,0.06,xauusd,1531.06000,1537.000,0.0000,2019.09.25 15:24:31,1527.40000,0.0,0,0,21.96,48644
83,83,25159303,2019.09.25 01:54:46,sell,0.01,xauusd,1531.28000,1537.000,0.0000,2019.09.25 15:24:35,1527.36000,0.0,0,0,3.92,48589

In [8]:
df_archivo['item'] = df_archivo['item'].replace('usdmxn-2','usdmxn').replace('wticousd-2','wticousd').replace('xauusd-2','xauusd').replace('xagusd-2','xagusd').replace('natgasusd-2','natgasusd').replace('gbpusd-2','gbpusd').replace('eurusd-2','eurusd')
df_archivo.head()

,index,order,open time,type,size,item,openprice,s/l,t/p,close time,closeprice,commission,taxes,swap,profit,Time
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92,8291
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73,48716
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00,5745
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27,48415
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34,116

In [9]:
Pips = df_archivo[['item','type','openprice','closeprice']]
Pips.index = np.arange(0,len(Pips))
Pips.head()

     item type   openprice  closeprice
0  xauusd  buy  1529.21000  1533.69000
1  eurjpy  buy   117.66400   117.37400
2  eurjpy  buy   117.34600   117.45200
3  eurusd  buy     1.10791     1.10818
4  gbpusd  buy     1.22024     1.21990

In [10]:
pip = []
contador = 0
for i in range(0,len(Pips)):
    if Pips['type'][i] == 'buy':
        f = Pips['item'][contador]
        multiplicador = f_pip_size(param_ins = f)
        pip.append((Pips['closeprice'][i] - Pips['openprice'][i]) * multiplicador)
    else:
        f = Pips['item'][contador]
        multiplicador = f_pip_size(param_ins = f)
        pip.append((Pips['openprice'][i] - Pips['closeprice'][i])*multiplicador)
    contador = contador + 1

Pips = pd.DataFrame(pip)
df_archivo['Pips'] = Pips
df_archivo

,index,order,open time,type,size,item,openprice,s/l,t/p,close time,closeprice,commission,taxes,swap,profit,Time,Pips
0,0,24316034,2019.08.27 06:57:50,buy,0.04,xauusd,1529.21000,1523.000,1543.0000,2019.08.27 09:16:01,1533.69000,0.0,0,0,17.92,8291,44.8
1,1,24334215,2019.08.27 17:06:20,buy,0.01,eurjpy,117.66400,116.950,118.7000,2019.08.29 06:38:16,117.37400,0.0,0,0,-2.73,48716,-29.0
2,2,24342155,2019.08.27 19:25:39,buy,0.05,eurjpy,117.34600,116.950,119.7000,2019.08.28 21:01:24,117.45200,0.0,0,0,5.00,5745,10.6
3,3,24373260,2019.08.28 17:11:33,buy,0.01,eurusd,1.10791,1.104,1.1175,2019.08.29 06:38:28,1.10818,0.0,0,0,0.27,48415,2.7
4,4,24392415,2019.08.29 06:35:27,buy,0.01,gbpusd,1.22024,1.208,1.2370,2019.08.29 06:37:23,1.21990,0.0,0,0,-0.34,116,-3.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,79,25148355,2019.09.24 20:09:52,sell,0.06,xauusd,1532.02000,1538.000,0.0000,2019.09.24 21:18:43,1525.66000,0.0,0,0,38.16,4131,63.6
80,80,25148480,2019.09.24 20:11:20,sell,0.02,xauusd,1531.50000,1538.000,0.0000,2019.09.24 21:18:46,1525.63000,0.0,0,0,11.74,4046,58.7
81,81,25148522,2019.09.24 20:12:41,sell,0.01,xauusd,1531.86000,1538.000,0.0000,2019.09.24 21:18:49,1525.66000,0.0,0,0,6.20,3968,62.0
82,82,25159294,2019.09.25 01:53:47,sell,0.06,xauusd,1531.06000,1537.000,0.0000,2019.09.25 15:24:31,1527.40000,0.0,0,0,21.96,48644,36.6
83,83,25159303,2019.09.25 01:54:46,sell,0.01,xauusd,1531.28000,1537.000,0.0000,2019.09.25 15:24:35,1527.36000,0.0,0,0,3.92,48589,39.2

In [13]:
Win = 0   #Ganadoras
Lose = 0  #Perdedoras
WinB = 0  #Ganadoras Compra
WinS = 0 #Ganadoras de Venta
LoseB = 0 #Perdedora Compra
LoseS = 0 #Perdedoras Venta


contador = 0

for i in range(0,len(df_archivo)):
    if df_archivo['type'][i] == 'buy':
        if df_archivo['Pips'][i] > 0:
            Win = Win + 1
            WinB = WinB + 1
        else:
            Lose = Lose + 1 
            LoseB = LoseB + 1
    else:
        if df_archivo['Pips'][i] > 0:
            Win = Win + 1
            WinS = WinS + 1
        else:
            Lose = Lose + 1 
            LoseS = LoseS + 1


Ops_totales = len(Pips)
r_efectividad  = Win / Ops_totales
r_porcion = Lose / Win
r_efectividad_c = WinB / Ops_totales
r_efectividad_v = WinS / Ops_totales
Media_Profit = df_archivo['profit'].mean()
Media_Pips = df_archivo['Pips'].mean()

In [14]:
df_1_tabla = pd.DataFrame (columns = ['Medida','Valor','Descripcion'])
df_1_tabla.Medida = ['Ops totales','Ganadoras','Ganadoras_c','Ganadoras_v','Perdedoras','Perdedoras_c','Perdedoras_v','Media (Profit)','Media (Pips)','r_efectividad','r_proporcion','r_efectividad_c','r_efectividad_v']
df_1_tabla.Descripcion = ['Operaciones totales','Operaciones ganadoras','Operaciones ganadoras de compra','Operaciones perdedoras de venta','Operaciones perdedoras','Operaciones perdedoras de compra','Operaciones perdedoras de venta','Mediana de profit de operaciones','Mediana de pips de operaciones','Ganadoras Totales/Operaciones Totales','Perdedoras Totales/Ganadoras Totales','Ganadoras Compras/Operaciones Totales','Ganadoras Ventas/ Operaciones Totales']
df_1_tabla.Valor = [Ops_totales, Win, WinB, WinS, Lose, LoseB, LoseS, Media_Profit, Media_Pips , r_efectividad, r_porcion, r_efectividad_c, r_efectividad_v,]
df_1_tabla

             Medida      Valor                            Descripcion
0       Ops totales  84.000000                    Operaciones totales
1         Ganadoras  46.000000                  Operaciones ganadoras
2       Ganadoras_c  20.000000        Operaciones ganadoras de compra
3       Ganadoras_v  26.000000        Operaciones perdedoras de venta
4        Perdedoras  38.000000                 Operaciones perdedoras
5      Perdedoras_c  19.000000       Operaciones perdedoras de compra
6      Perdedoras_v  19.000000        Operaciones perdedoras de venta
7    Media (Profit)   3.025357       Mediana de profit de operaciones
8      Media (Pips)  29.066667         Mediana de pips de operaciones
9     r_efectividad   0.547619  Ganadoras Totales/Operaciones Totales
10     r_proporcion   0.826087   Perdedoras Totales/Ganadoras Totales
11  r_efectividad_c   0.238095  Ganadoras Compras/Operaciones Totales
12  r_efectividad_v   0.309524  Ganadoras Ventas/ Operaciones Totales

In [26]:
efec = df_archivo[['item','profit']]
count_movi = efec.groupby('item').count()
count_posit = efec[efec['profit'] > 0].groupby([efec['item']])
count_posit = count_posit.count()
Efectividad = ((count_posit['profit'] / count_movi['profit'] ) * 100).round(4)
Efectividad = pd.DataFrame(Efectividad)

In [27]:
Porcentaje  = [str(l) + "%" for l in Efectividad.profit]
Efectividad.profit = Porcentaje
Ratio_efect = pd.DataFrame(Porcentaje)
Efectividad.rename(columns = {'profit':'rank'})
New = Efectividad.reset_index()
New.rename(columns={'item':'symbol'})

    symbol    profit
0   audusd  33.3333%
1   btcusd    100.0%
2   eurgbp    100.0%
3   eurjpy  28.5714%
4   eurusd  47.8261%
5   gbpjpy     25.0%
6   gbpusd  66.6667%
7   usdcad  28.5714%
8   usdjpy     60.0%
9   usdmxn     80.0%
10  xauusd  73.6842%